import type { LandingContent } from './types';
import {
  cameraProduct,
  headphoneProduct,
  palystaytionProduct,
  productImageUrls,
  smartwatchProduct,
} from './shared';

export const enLandingContent: LandingContent = {
  navLinks: [
    { href: '/', label: 'Home' },
    { href: '/about', label: 'About' },
    { href: '/contact', label: 'Contact' },
    { href: '/blog', label: 'Blog' },
  ],
  footerContent: {
    brand: 'HooshmandSazan',
    tagline:
      'Online store for digital products with fast shipping and authenticity guarantee.',
    columns: [
      {
        title: 'Company',
        links: [
          { href: '/', label: 'Home' },
          { href: '/about', label: 'About' },
          { href: '/contact', label: 'Contact' },
          { href: '/blog', label: 'Blog' },
        ],
      },
      {
        title: 'Support',
        links: [
          { href: '/faq', label: 'FAQ' },
          { href: '/shipping', label: 'Shipping & delivery' },
          { href: '/returns', label: 'Returns' },
          { href: '/privacy', label: 'Privacy' },
        ],
      },
    ],
    contact: {
      phone: '+98 21 1234 5678',
      email: 'info@rahpooyan.ir',
      address: 'Valiasr St, Tehran',
    },
    social: [
      {
        href: 'https://instagram.com',
        label: 'Instagram',
        icon: 'lucide:instagram',
      },
      { href: 'https://t.me', label: 'Telegram', icon: 'lucide:send' },
      {
        href: 'https://linkedin.com',
        label: 'LinkedIn',
        icon: 'lucide:linkedin',
      },
    ],
    legal: [
      { href: '/terms', label: 'Terms & conditions' },
      { href: '/privacy', label: 'Privacy' },
    ],
    copyright: '© 2026 HooshmandSazan. All rights reserved.',
  },
  categoryBarItems: [
    { slug: 'phones', label: 'Phones' },
    { slug: 'computers', label: 'Computers' },
    { slug: 'watches', label: 'Smartwatches' },
    { slug: 'cameras', label: 'Cameras' },
    { slug: 'headphones', label: 'Headphones' },
    { slug: 'gaming', label: 'Gaming' },
  ],
  browseCategories: [
    { slug: 'phones', label: 'Phones', icon: 'lucide:smartphone' },
    { slug: 'watches', label: 'Smartwatches', icon: 'lucide:watch' },
    { slug: 'cameras', label: 'Cameras', icon: 'lucide:camera' },
    { slug: 'headphones', label: 'Headphones', icon: 'lucide:headphones' },
    { slug: 'computers', label: 'Computers', icon: 'lucide:monitor' },
    { slug: 'gaming', label: 'Gaming', icon: 'lucide:gamepad-2' },
  ],
  productTabs: [
    { id: 'new', label: 'New arrivals' },
    { id: 'bestseller', label: 'Best sellers' },
    { id: 'featured', label: 'Featured' },
  ],
  productsByTab: {
    new: [
      {
        id: '1',
        name: 'Smartphone X 128GB',
        price: '$499',
        compareAtPrice: '$769',
        discountPercent: 35,
        image: productImageUrls.phone,
        imageAlt: 'Smartphone X 128GB',
      },
      {
        id: '2',
        name: 'Cinematic pocket pro camera',
        price: '$799',
        image: productImageUrls.camera,
        imageAlt: 'Cinematic pocket pro camera',
      },
      {
        id: '3',
        name: 'Sport smartwatch series 9',
        price: '$199',
        image: productImageUrls.smartwatch,
        imageAlt: 'Sport smartwatch series 9',
      },
      {
        id: '4',
        name: 'Silver wireless pro headphones',
        price: '$159',
        compareAtPrice: '$245',
        discountPercent: 35,
        image: productImageUrls.headphone,
        imageAlt: 'Silver wireless pro headphones',
      },
      {
        id: '5',
        name: 'Classic 47mm smartwatch',
        price: '$189',
        image: productImageUrls.smartwatch,
        imageAlt: 'Classic 47mm smartwatch',
      },
      {
        id: '6',
        name: 'Next-gen foldable phone 256GB',
        price: '$899',
        defaultFavorite: true,
        image: productImageUrls.foldPhone,
        imageAlt: 'Next-gen foldable phone 256GB',
      },
      {
        id: '7',
        name: 'Graffiti wireless earbuds',
        price: '$59',
        compareAtPrice: '$89',
        discountPercent: 35,
        image: productImageUrls.earbuds,
        imageAlt: 'Graffiti wireless earbuds',
      },
      {
        id: '8',
        name: '10.2" tablet 64GB',
        price: '$349',
        image: productImageUrls.tablet,
        imageAlt: '10.2 inch tablet 64GB',
      },
    ],
    bestseller: [
      {
        id: 'b1',
        name: '14" ultrabook laptop',
        price: '$1,199',
        compareAtPrice: '$1,499',
        discountPercent: 22,
        image: productImageUrls.laptop,
        imageAlt: '14 inch ultrabook laptop',
      },
      {
        id: 'b2',
        name: 'Next-gen gaming console',
        price: '$499',
        image: productImageUrls.gamingConsole,
        imageAlt: 'Next-gen gaming console',
      },
      {
        id: 'b3',
        name: 'Galaxy Buds',
        price: '$89',
        compareAtPrice: '$139',
        discountPercent: 35,
        image: productImageUrls.headphone2,
        imageAlt: 'Galaxy Buds',
      },
      {
        id: 'b4',
        name: 'Portable Bluetooth speaker',
        price: '$49',
        compareAtPrice: '$59',
        discountPercent: 15,
        image: productImageUrls.speaker,
        imageAlt: 'Portable Bluetooth speaker',
      },
      {
        id: 'b5',
        name: 'Pro Max smartphone',
        price: '$699',
        compareAtPrice: '$899',
        discountPercent: 20,
        image: productImageUrls.phone,
        imageAlt: 'Pro Max smartphone',
      },
      {
        id: 'b6',
        name: 'Sport series smartwatch',
        price: '$179',
        image: productImageUrls.smartwatch,
        imageAlt: 'Sport series smartwatch',
      },
      {
        id: 'b7',
        name: 'Noise-cancelling headphones',
        price: '$249',
        compareAtPrice: '$359',
        discountPercent: 30,
        image: productImageUrls.headphone,
        imageAlt: 'Noise-cancelling headphones',
      },
      {
        id: 'b8',
        name: '24MP mirrorless camera',
        price: '$1,299',
        image: productImageUrls.mirrorlessCamera,
        imageAlt: '24MP mirrorless camera',
      },
    ],
    featured: [
      {
        id: 'f1',
        name: '11" pro tablet',
        price: '$649',
        image: productImageUrls.tablet,
        imageAlt: '11 inch pro tablet',
      },
      {
        id: 'f2',
        name: '20,000mAh fast-charge power bank',
        price: '$29',
        compareAtPrice: '$39',
        discountPercent: 21,
        image: productImageUrls.powerBank,
        imageAlt: '20,000mAh fast-charge power bank',
      },
      {
        id: 'f3',
        name: 'AK-900 mechanical keyboard',
        price: '$89',
        compareAtPrice: '$139',
        discountPercent: 35,
        image: productImageUrls.keyboard,
        imageAlt: 'AK-900 mechanical keyboard',
      },
      {
        id: 'f4',
        name: 'Ergonomic gaming mouse',
        price: '$59',
        image: productImageUrls.mouse,
        imageAlt: 'Ergonomic gaming mouse',
      },
      {
        id: 'f5',
        name: 'Smart home speaker',
        price: '$129',
        image: productImageUrls.smartSpeaker,
        imageAlt: 'Smart home speaker',
      },
      {
        id: 'f6',
        name: "Women's smartwatch",
        price: '$159',
        image: productImageUrls.smartwatch,
        imageAlt: "Women's smartwatch",
      },
      {
        id: 'f7',
        name: '16" gaming laptop',
        price: '$1,899',
        image: productImageUrls.gamingLaptop,
        imageAlt: '16 inch gaming laptop',
      },
      {
        id: 'f8',
        name: 'Studio wired headphones',
        price: '$149',
        image: productImageUrls.studioHeadphones,
        imageAlt: 'Studio wired headphones',
      },
    ],
  },
  cardSwapSection: {
    title: 'Special offers',
    description: 'See the next deal every few seconds.',
    cta: 'View all',
    href: '/products?tab=featured',
    ariaLabel: 'Special offers',
  },
  cardSwapPromos: [
    {
      id: 'iphone',
      eyebrow: 'Pro. Beyond.',
      title: 'iPhone 14 Pro',
      description: 'Designed to make everything better for everyone.',
      image:
        'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&auto=format&fit=crop&q=80',
      imageAlt: 'iPhone 14 Pro',
      cta: 'Shop',
      href: '/products',
    },
    {
      id: 'ps5',
      eyebrow: 'Gaming',
      title: 'PlayStation 5',
      description: 'Experience next-gen games with stunning graphics.',
      image:
        'https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=1200&auto=format&fit=crop&q=80',
      imageAlt: 'PlayStation 5',
      cta: 'Explore',
      href: '/products/category/gaming',
    },
    {
      id: 'macbook',
      eyebrow: 'Apple',
      title: 'MacBook Air',
      description: 'Powerful. Light. Ready to move.',
      image:
        'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
      imageAlt: 'MacBook Air',
      cta: 'Shop',
      href: '/products',
    },
    {
      id: 'headphones',
      eyebrow: 'Audio',
      title: 'Wireless Pro Headphones',
      description:
        'Clear sound with active noise cancellation for any environment.',
      image: headphoneProduct.src,
      imageAlt: 'Galaxy Buds',
      cta: 'Shop',
      href: '/products/category/headphones',
    },
    {
      id: 'watch',
      eyebrow: 'Wearables',
      title: 'Smartwatch Series 9',
      description: 'Health, fitness, and always-on connectivity on your wrist.',
      image:
        'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
      imageAlt: 'Smartwatch Series 9',
      cta: 'Explore',
      href: '/products/category/watches',
    },
  ],
  newArrivalSection: {
    eyebrow: 'Featured',
    title: 'New arrivals',
    shopNowLabel: 'Shop now',
  },
  newArrivalCategories: [
    {
      slug: 'gaming',
      title: 'Gaming',
      description: 'Consoles, accessories, and pro gaming gear.',
      image: palystaytionProduct,
      imageAlt: 'Gaming console',
      href: '/products/category/gaming',
    },
    {
      slug: 'phones',
      title: 'Phones',
      description: 'Latest smartphones with special offers.',
      image:
        'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=1400&auto=format&fit=crop&q=90',
      imageAlt: 'Smartphone',
      href: '/products/category/phones',
    },
    {
      slug: 'headphones',
      title: 'Headphones',
      description: 'High-quality wireless headphones and speakers.',
      image: headphoneProduct,
      imageAlt: 'Wireless headphones',
      href: '/products/category/headphones',
    },
    {
      slug: 'watches',
      title: 'Smartwatches',
      description: 'Smart wearables for a modern lifestyle.',
      image: smartwatchProduct,
      imageAlt: 'Smartwatch',
      href: '/products/category/watches',
    },
  ],
  serviceHighlights: [
    {
      id: 'delivery',
      icon: 'lucide:truck',
      title: 'Free & fast delivery',
      description: 'Free shipping on orders over $100',
    },
    {
      id: 'support',
      icon: 'lucide:headset',
      title: '24/7 support',
      description: 'Friendly help around the clock',
    },
    {
      id: 'guarantee',
      icon: 'lucide:shield-check',
      title: 'Money-back guarantee',
      description: 'Full refund within 30 days of purchase',
    },
  ],
  categoryBrowse: {
    title: 'Browse by category',
    prevLabel: 'Previous category',
    nextLabel: 'Next category',
    categoriesAriaLabel: 'Product categories',
  },
  serviceHighlightsAria: 'Store services',
  home: {
    newProductsEyebrow: 'This month',
    newProductsTitle: 'Newest products',
    bestsellersEyebrow: 'This month',
    bestsellersTitle: 'Best-selling products',
    viewAll: 'View all',
  },
  promoBanners: [
    {
      id: 'ps5',
      title: 'PlayStation 5',
      description: 'Experience next-gen gaming.',
      align: 'image-start',
      tone: 'light',
    },
    {
      id: 'macbook',
      title: 'MacBook Air',
      description: 'Powerful. Light. Ready to move.',
      align: 'image-end',
      tone: 'muted',
      cta: 'Shop',
    },
  ],
};
