import type { LandingContent } from './types';
import {
  cameraProduct,
  headphoneProduct,
  palystaytionProduct,
  productImageUrls,
  smartwatchProduct,
} from './shared';

export const faLandingContent: LandingContent = {
  navLinks: [
    { href: '/', label: 'خانه' },
    { href: '/about', label: 'درباره ما' },
    { href: '/contact', label: 'تماس با ما' },
    { href: '/blog', label: 'وبلاگ' },
  ],
  footerContent: {
    brand: 'رهپویان',
    tagline: 'فروشگاه آنلاین محصولات دیجیتال با ارسال سریع و ضمانت اصالت کالا.',
    columns: [
      {
        title: 'شرکت',
        links: [
          { href: '/', label: 'خانه' },
          { href: '/about', label: 'درباره ما' },
          { href: '/contact', label: 'تماس با ما' },
          { href: '/blog', label: 'وبلاگ' },
        ],
      },
      {
        title: 'پشتیبانی',
        links: [
          { href: '/faq', label: 'سوالات متداول' },
          { href: '/shipping', label: 'ارسال و تحویل' },
          { href: '/returns', label: 'مرجوعی کالا' },
          { href: '/privacy', label: 'حریم خصوصی' },
        ],
      },
    ],
    contact: {
      phone: '۰۲۱-۱۲۳۴۵۶۷۸',
      email: 'info@rahpooyan.ir',
      address: 'تهران، خیابان ولیعصر',
    },
    social: [
      {
        href: 'https://instagram.com',
        label: 'اینستاگرام',
        icon: 'lucide:instagram',
      },
      { href: 'https://t.me', label: 'تلگرام', icon: 'lucide:send' },
      {
        href: 'https://linkedin.com',
        label: 'لینکدین',
        icon: 'lucide:linkedin',
      },
    ],
    legal: [
      { href: '/terms', label: 'قوانین و مقررات' },
      { href: '/privacy', label: 'حریم خصوصی' },
    ],
    copyright: '© ۱۴۰۵ رهپویان. تمامی حقوق محفوظ است.',
  },
  categoryBarItems: [
    { slug: 'phones', label: 'موبایل' },
    { slug: 'computers', label: 'کامپیوتر' },
    { slug: 'watches', label: 'ساعت هوشمند' },
    { slug: 'cameras', label: 'دوربین' },
    { slug: 'headphones', label: 'هدفون' },
    { slug: 'gaming', label: 'گیمینگ' },
  ],
  browseCategories: [
    { slug: 'phones', label: 'موبایل', icon: 'lucide:smartphone' },
    { slug: 'watches', label: 'ساعت هوشمند', icon: 'lucide:watch' },
    { slug: 'cameras', label: 'دوربین', icon: 'lucide:camera' },
    { slug: 'headphones', label: 'هدفون', icon: 'lucide:headphones' },
    { slug: 'computers', label: 'کامپیوتر', icon: 'lucide:monitor' },
    { slug: 'gaming', label: 'گیمینگ', icon: 'lucide:gamepad-2' },
  ],
  productTabs: [
    { id: 'new', label: 'جدیدترین‌ها' },
    { id: 'bestseller', label: 'پرفروش‌ها' },
    { id: 'featured', label: 'پیشنهادهای ویژه' },
  ],
  productsByTab: {
    new: [
      {
        id: '1',
        name: 'گوشی هوشمند ایکس ۱۲۸ گیگابایت',
        price: '۲۴٫۹۰۰٫۰۰۰ تومان',
        compareAtPrice: '۳۸٫۳۰۰٫۰۰۰ تومان',
        discountPercent: 35,
        image: productImageUrls.phone,
        imageAlt: 'گوشی هوشمند ایکس ۱۲۸ گیگابایت',
      },
      {
        id: '2',
        name: 'دوربین حرفه‌ای جیبی سینمایی',
        price: '۳۸٫۲۰۰٫۰۰۰ تومان',
        image: productImageUrls.camera,
        imageAlt: 'دوربین حرفه‌ای جیبی سینمایی',
      },
      {
        id: '3',
        name: 'ساعت هوشمند اسپرت سری ۹',
        price: '۸٫۹۰۰٫۰۰۰ تومان',
        image: productImageUrls.smartwatch,
        imageAlt: 'ساعت هوشمند اسپرت سری ۹',
      },
      {
        id: '4',
        name: 'هدفون بی‌سیم پرو نقره‌ای',
        price: '۱۰٫۰۱۰٫۰۰۰ تومان',
        compareAtPrice: '۱۵٫۴۰۰٫۰۰۰ تومان',
        discountPercent: 35,
        image: productImageUrls.headphone,
        imageAlt: 'هدفون بی‌سیم پرو نقره‌ای',
      },
      {
        id: '5',
        name: 'ساعت هوشمند کلاسیک ۴۷ میلی‌متر',
        price: '۹٫۸۰۰٫۰۰۰ تومان',
        image: productImageUrls.smartwatch,
        imageAlt: 'ساعت هوشمند کلاسیک ۴۷ میلی‌متر',
      },
      {
        id: '6',
        name: 'گوشی تاشو نسل جدید ۲۵۶ گیگابایت',
        price: '۴۲٫۰۰۰٫۰۰۰ تومان',
        defaultFavorite: true,
        image: productImageUrls.foldPhone,
        imageAlt: 'گوشی تاشو نسل جدید ۲۵۶ گیگابایت',
      },
      {
        id: '7',
        name: 'ایربادز بی‌سیم گرافیتی',
        price: '۲٫۹۰۰٫۰۰۰ تومان',
        compareAtPrice: '۴٫۵۰۰٫۰۰۰ تومان',
        discountPercent: 35,
        image: productImageUrls.earbuds,
        imageAlt: 'ایربادز بی‌سیم گرافیتی',
      },
      {
        id: '8',
        name: 'تبلت ۱۰.۲ اینچی ۶۴ گیگابایت',
        price: '۱۴٫۵۰۰٫۰۰۰ تومان',
        image: productImageUrls.tablet,
        imageAlt: 'تبلت ۱۰.۲ اینچی ۶۴ گیگابایت',
      },
    ],
    bestseller: [
      {
        id: 'b1',
        name: 'لپ‌تاپ اولترابوک ۱۴ اینچی',
        price: '۴۵٫۰۰۰٫۰۰۰ تومان',
        compareAtPrice: '۵۸٫۰۰۰٫۰۰۰ تومان',
        discountPercent: 22,
        image: productImageUrls.laptop,
        imageAlt: 'لپ‌تاپ اولترابوک ۱۴ اینچی',
      },
      {
        id: 'b2',
        name: 'کنسول بازی نسل جدید',
        price: '۲۲٫۰۰۰٫۰۰۰ تومان',
        image: productImageUrls.gamingConsole,
        imageAlt: 'کنسول بازی نسل جدید',
      },
      {
        id: 'b3',
        name: 'Glaxy buds',
        price: '۳٫۱۲۰٫۰۰۰ تومان',
        compareAtPrice: '۴٫۸۰۰٫۰۰۰ تومان',
        discountPercent: 35,
        image: productImageUrls.headphone2,
        imageAlt: 'Glaxy buds',
      },
      {
        id: 'b4',
        name: 'اسپیکر بلوتوثی پرتابل',
        price: '۱٫۷۸۵٫۰۰۰ تومان',
        compareAtPrice: '۲٫۱۰۰٫۰۰۰ تومان',
        discountPercent: 15,
        image: productImageUrls.speaker,
        imageAlt: 'اسپیکر بلوتوثی پرتابل',
      },
      {
        id: 'b5',
        name: 'گوشی هوشمند پرو مکس',
        price: '۲۶٫۰۰۰٫۰۰۰ تومان',
        compareAtPrice: '۳۲٫۵۰۰٫۰۰۰ تومان',
        discountPercent: 20,
        image: productImageUrls.phone,
        imageAlt: 'گوشی هوشمند پرو مکس',
      },
      {
        id: 'b6',
        name: 'ساعت هوشمند سری اسپرت',
        price: '۷٫۲۰۰٫۰۰۰ تومان',
        image: productImageUrls.smartwatch,
        imageAlt: 'ساعت هوشمند سری اسپرت',
      },
      {
        id: 'b7',
        name: 'هدفون نویز کنسلینگ',
        price: '۹٫۰۳۰٫۰۰۰ تومان',
        compareAtPrice: '۱۲٫۹۰۰٫۰۰۰ تومان',
        discountPercent: 30,
        image: productImageUrls.headphone,
        imageAlt: 'هدفون نویز کنسلینگ',
      },
      {
        id: 'b8',
        name: 'دوربین بدون آینه ۲۴ مگاپیکسل',
        price: '۳۵٫۰۰۰٫۰۰۰ تومان',
        image: productImageUrls.mirrorlessCamera,
        imageAlt: 'دوربین بدون آینه ۲۴ مگاپیکسل',
      },
    ],
    featured: [
      {
        id: 'f1',
        name: 'تبلت ۱۱ اینچی پرو',
        price: '۲۸٫۵۰۰٫۰۰۰ تومان',
        image: productImageUrls.tablet,
        imageAlt: 'تبلت ۱۱ اینچی پرو',
      },
      {
        id: 'f2',
        name: 'پاوربانک فست شارژ ۲۰ هزار',
        price: '۹۹۰٫۰۰۰ تومان',
        compareAtPrice: '۱٫۲۵۰٫۰۰۰ تومان',
        discountPercent: 21,
        image: productImageUrls.powerBank,
        imageAlt: 'پاوربانک فست شارژ ۲۰ هزار',
      },
      {
        id: 'f3',
        name: 'کیبورد مکانیکال AK-900',
        price: '۲٫۵۳۵٫۰۰۰ تومان',
        compareAtPrice: '۳٫۹۰۰٫۰۰۰ تومان',
        discountPercent: 35,
        image: productImageUrls.keyboard,
        imageAlt: 'کیبورد مکانیکال AK-900',
      },
      {
        id: 'f4',
        name: 'ماوس ارگونومیک گیمینگ',
        price: '۱٫۸۰۰٫۰۰۰ تومان',
        image: productImageUrls.mouse,
        imageAlt: 'ماوس ارگونومیک گیمینگ',
      },
      {
        id: 'f5',
        name: 'اسپیکر هوشمند خانگی',
        price: '۴٫۵۰۰٫۰۰۰ تومان',
        image: productImageUrls.smartSpeaker,
        imageAlt: 'اسپیکر هوشمند خانگی',
      },
      {
        id: 'f6',
        name: 'ساعت هوشمند بانوان',
        price: '۶٫۲۰۰٫۰۰۰ تومان',
        image: productImageUrls.smartwatch,
        imageAlt: 'ساعت هوشمند بانوان',
      },
      {
        id: 'f7',
        name: 'لپ‌تاپ گیمینگ ۱۶ اینچی',
        price: '۶۸٫۰۰۰٫۰۰۰ تومان',
        image: productImageUrls.gamingLaptop,
        imageAlt: 'لپ‌تاپ گیمینگ ۱۶ اینچی',
      },
      {
        id: 'f8',
        name: 'هدفون استودیویی سیمی',
        price: '۵٫۴۰۰٫۰۰۰ تومان',
        image: productImageUrls.studioHeadphones,
        imageAlt: 'هدفون استودیویی سیمی',
      },
    ],
  },
  cardSwapSection: {
    title: 'پیشنهادهای ویژه',
    description: 'هر چند ثانیه پیشنهاد بعدی را ببینید.',
    cta: 'مشاهده همه',
    href: '/products?tab=featured',
    ariaLabel: 'پیشنهادهای ویژه',
  },
  cardSwapPromos: [
    {
      id: 'iphone',
      eyebrow: 'حرفه‌ای. فراتر.',
      title: 'آیفون ۱۴ پرو',
      description: 'طراحی شده تا همه‌چیز را برای همه، بهتر کند.',
      image:
        'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&auto=format&fit=crop&q=80',
      imageAlt: 'آیفون ۱۴ پرو',
      cta: 'خرید',
      href: '/products',
    },
    {
      id: 'ps5',
      eyebrow: 'گیمینگ',
      title: 'پلی‌استیشن ۵',
      description: 'تجربه نسل جدید بازی‌ها با گرافیک خیره‌کننده.',
      image:
        'https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=1200&auto=format&fit=crop&q=80',
      imageAlt: 'پلی‌استیشن ۵',
      cta: 'مشاهده',
      href: '/products/category/gaming',
    },
    {
      id: 'macbook',
      eyebrow: 'محصولات اپل',
      title: 'مک‌بوک ایر',
      description: 'قدرتمند. سبک. آماده حرکت.',
      image:
        'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
      imageAlt: 'مک‌بوک ایر',
      cta: 'خرید',
      href: '/products',
    },
    {
      id: 'headphones',
      eyebrow: 'صوت',
      title: 'هدفون بی‌سیم پرو',
      description: 'صدای شفاف با حذف نویز فعال برای هر محیط.',
      image: headphoneProduct.src,
      imageAlt: 'Glaxy buds',
      cta: 'خرید',
      href: '/products/category/headphones',
    },
    {
      id: 'watch',
      eyebrow: 'پوشیدنی',
      title: 'ساعت هوشمند سری ۹',
      description: 'سلامت، تناسب اندام و اتصال همیشگی در مچ دست.',
      image:
        'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
      imageAlt: 'ساعت هوشمند سری ۹',
      cta: 'مشاهده',
      href: '/products/category/watches',
    },
  ],
  newArrivalSection: {
    eyebrow: 'منتخب',
    title: 'تازه ها',
    shopNowLabel: 'خرید کنید',
  },
  newArrivalCategories: [
    {
      slug: 'gaming',
      title: 'گیمینگ',
      description: 'کنسول‌ها، لوازم جانبی و تجهیزات حرفه‌ای بازی.',
      image: palystaytionProduct,
      imageAlt: 'کنسول بازی',
      href: '/products/category/gaming',
    },
    {
      slug: 'phones',
      title: 'موبایل',
      description: 'جدیدترین گوشی‌های هوشمند با پیشنهادهای ویژه.',
      image:
        'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=1400&auto=format&fit=crop&q=90',
      imageAlt: 'گوشی هوشمند',
      href: '/products/category/phones',
    },
    {
      slug: 'headphones',
      title: 'هدفون',
      description: 'هدفون و اسپیکرهای بی‌سیم با کیفیت بالا.',
      image: headphoneProduct,
      imageAlt: 'هدفون بی‌سیم',
      href: '/products/category/headphones',
    },
    {
      slug: 'watches',
      title: 'ساعت هوشمند',
      description: 'پوشیدنی‌های هوشمند برای سبک زندگی مدرن.',
      image: smartwatchProduct,
      imageAlt: 'ساعت هوشمند',
      href: '/products/category/watches',
    },
  ],
  serviceHighlights: [
    {
      id: 'delivery',
      icon: 'lucide:truck',
      title: 'ارسال رایگان و سریع',
      description: 'ارسال رایگان برای سفارش‌های بالای ۵ میلیون تومان',
    },
    {
      id: 'support',
      icon: 'lucide:headset',
      title: 'پشتیبانی ۲۴ ساعته',
      description: 'پشتیبانی دوستانه در تمام ساعات شبانه‌روز',
    },
    {
      id: 'guarantee',
      icon: 'lucide:shield-check',
      title: 'ضمانت بازگشت وجه',
      description: 'بازگشت وجه تا ۳۰ روز پس از خرید',
    },
  ],
  categoryBrowse: {
    title: 'مرور بر اساس دسته',
    prevLabel: 'دسته قبلی',
    nextLabel: 'دسته بعدی',
    categoriesAriaLabel: 'دسته‌بندی محصولات',
  },
  serviceHighlightsAria: 'خدمات فروشگاه',
  home: {
    newProductsEyebrow: 'این ماه',
    newProductsTitle: 'جدیدترین محصولات',
    bestsellersEyebrow: 'این ماه',
    bestsellersTitle: 'پرفروش‌ترین محصولات',
    viewAll: 'مشاهده همه',
  },
  promoBanners: [
    {
      id: 'ps5',
      title: 'پلی‌استیشن ۵',
      description: 'تجربه نسل جدید بازی‌ها.',
      align: 'image-start',
      tone: 'light',
    },
    {
      id: 'macbook',
      title: 'مک‌بوک ایر',
      description: 'قدرتمند. سبک. آماده حرکت.',
      align: 'image-end',
      tone: 'muted',
      cta: 'خرید',
    },
  ],
};
